- name: Setup MongoDB
  hosts: mongodb
  become: true
  roles:
    - database
    - opentelemetry

- name: Setup Titra app
  hosts: titra
  become: true
  roles:
    - application
    - opentelemetry

- name: Setup nginx
  hosts: nginx
  become: true
  roles:
    - proxy
    - opentelemetry